name: CrashPayment
version: 1.0
main: net.crashcraft.crashpayment.CrashPayment
website: http://Crashcraft.net
loadbefore: []
description: A core that can crash
depend: []
softdepend: [Vault]
api-version: 1.16